Canobie.Repo.insert!(%Canobie.Team{id: 1, name: "Team 1"})
Canobie.Repo.insert!(%Canobie.State{team_id: 1, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 1, name: "badler"})
Canobie.Repo.insert!(%Canobie.User{team_id: 1, name: "mgray"})
Canobie.Repo.insert!(%Canobie.User{team_id: 1, name: "twieczorek"})
Canobie.Repo.insert!(%Canobie.User{team_id: 1, name: "afinn"})
Canobie.Repo.insert!(%Canobie.Team{id: 2, name: "Team 2"})
Canobie.Repo.insert!(%Canobie.State{team_id: 2, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 2, name: "aaverill"})
Canobie.Repo.insert!(%Canobie.User{team_id: 2, name: "gsalmon"})
Canobie.Repo.insert!(%Canobie.User{team_id: 2, name: "arollins"})
Canobie.Repo.insert!(%Canobie.User{team_id: 2, name: "noliveri"})
Canobie.Repo.insert!(%Canobie.Team{id: 3, name: "Team 3"})
Canobie.Repo.insert!(%Canobie.State{team_id: 3, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 3, name: "kflanagan"})
Canobie.Repo.insert!(%Canobie.User{team_id: 3, name: "cherman"})
Canobie.Repo.insert!(%Canobie.User{team_id: 3, name: "zaghion"})
Canobie.Repo.insert!(%Canobie.User{team_id: 3, name: "jleahy"})
Canobie.Repo.insert!(%Canobie.Team{id: 4, name: "Team 4"})
Canobie.Repo.insert!(%Canobie.State{team_id: 4, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 4, name: "dsbordone"})
Canobie.Repo.insert!(%Canobie.User{team_id: 4, name: "dbrown"})
Canobie.Repo.insert!(%Canobie.User{team_id: 4, name: "pmurphy"})
Canobie.Repo.insert!(%Canobie.User{team_id: 4, name: "amunir"})
Canobie.Repo.insert!(%Canobie.Team{id: 5, name: "Team 5"})
Canobie.Repo.insert!(%Canobie.State{team_id: 5, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 5, name: "dclinton"})
Canobie.Repo.insert!(%Canobie.User{team_id: 5, name: "jdsouza"})
Canobie.Repo.insert!(%Canobie.User{team_id: 5, name: "mdilawari"})
Canobie.Repo.insert!(%Canobie.User{team_id: 5, name: "tpearson"})
Canobie.Repo.insert!(%Canobie.Team{id: 6, name: "Team 6"})
Canobie.Repo.insert!(%Canobie.State{team_id: 6, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 6, name: "dfloyd"})
Canobie.Repo.insert!(%Canobie.User{team_id: 6, name: "sradkiewicz"})
Canobie.Repo.insert!(%Canobie.User{team_id: 6, name: "hliu"})
Canobie.Repo.insert!(%Canobie.User{team_id: 6, name: "jmcintyre"})
Canobie.Repo.insert!(%Canobie.Team{id: 7, name: "Team 7"})
Canobie.Repo.insert!(%Canobie.State{team_id: 7, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 7, name: "dmccaffrey"})
Canobie.Repo.insert!(%Canobie.User{team_id: 7, name: "jlopes"})
Canobie.Repo.insert!(%Canobie.User{team_id: 7, name: "bbo"})
Canobie.Repo.insert!(%Canobie.User{team_id: 7, name: "mcanas"})
Canobie.Repo.insert!(%Canobie.Team{id: 8, name: "Team 8"})
Canobie.Repo.insert!(%Canobie.State{team_id: 8, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 8, name: "gspaulding"})
Canobie.Repo.insert!(%Canobie.User{team_id: 8, name: "aspitz"})
Canobie.Repo.insert!(%Canobie.User{team_id: 8, name: "jhilker"})
Canobie.Repo.insert!(%Canobie.User{team_id: 8, name: "tsimmons"})
Canobie.Repo.insert!(%Canobie.Team{id: 9, name: "Team 9"})
Canobie.Repo.insert!(%Canobie.State{team_id: 9, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 9, name: "jreynolds"})
Canobie.Repo.insert!(%Canobie.User{team_id: 9, name: "crollock"})
Canobie.Repo.insert!(%Canobie.User{team_id: 9, name: "jhahn"})
Canobie.Repo.insert!(%Canobie.User{team_id: 9, name: "kkamra"})
Canobie.Repo.insert!(%Canobie.Team{id: 10, name: "Team 10"})
Canobie.Repo.insert!(%Canobie.State{team_id: 10, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 10, name: "jaliperti"})
Canobie.Repo.insert!(%Canobie.User{team_id: 10, name: "jsolmon"})
Canobie.Repo.insert!(%Canobie.User{team_id: 10, name: "mbarackman"})
Canobie.Repo.insert!(%Canobie.User{team_id: 10, name: "wyoumans"})
Canobie.Repo.insert!(%Canobie.Team{id: 11, name: "Team 11"})
Canobie.Repo.insert!(%Canobie.State{team_id: 11, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 11, name: "jgreene"})
Canobie.Repo.insert!(%Canobie.User{team_id: 11, name: "mklos"})
Canobie.Repo.insert!(%Canobie.User{team_id: 11, name: "ntenczar"})
Canobie.Repo.insert!(%Canobie.User{team_id: 11, name: "ddangelo"})
Canobie.Repo.insert!(%Canobie.Team{id: 12, name: "Team 12"})
Canobie.Repo.insert!(%Canobie.State{team_id: 12, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 12, name: "bflanagan"})
Canobie.Repo.insert!(%Canobie.User{team_id: 12, name: "jtodd"})
Canobie.Repo.insert!(%Canobie.User{team_id: 12, name: "rmendiola"})
Canobie.Repo.insert!(%Canobie.User{team_id: 12, name: "mtrigonis"})
Canobie.Repo.insert!(%Canobie.Team{id: 13, name: "Team 13"})
Canobie.Repo.insert!(%Canobie.State{team_id: 13, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 13, name: "kmckinley"})
Canobie.Repo.insert!(%Canobie.User{team_id: 13, name: "cciollaro"})
Canobie.Repo.insert!(%Canobie.User{team_id: 13, name: "jpage"})
Canobie.Repo.insert!(%Canobie.User{team_id: 13, name: "jmckibben"})
Canobie.Repo.insert!(%Canobie.Team{id: 14, name: "Team 14"})
Canobie.Repo.insert!(%Canobie.State{team_id: 14, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 14, name: "kcronin"})
Canobie.Repo.insert!(%Canobie.User{team_id: 14, name: "bjacobel"})
Canobie.Repo.insert!(%Canobie.User{team_id: 14, name: "jrosen"})
Canobie.Repo.insert!(%Canobie.User{team_id: 14, name: "jtanenbaum"})
Canobie.Repo.insert!(%Canobie.Team{id: 15, name: "Team 15"})
Canobie.Repo.insert!(%Canobie.State{team_id: 15, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 15, name: "hcipolla"})
Canobie.Repo.insert!(%Canobie.User{team_id: 15, name: "mgoddard"})
Canobie.Repo.insert!(%Canobie.User{team_id: 15, name: "glovett"})
Canobie.Repo.insert!(%Canobie.User{team_id: 15, name: "klisacki"})
Canobie.Repo.insert!(%Canobie.Team{id: 16, name: "Team 16"})
Canobie.Repo.insert!(%Canobie.State{team_id: 16, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 16, name: "lorfanos"})
Canobie.Repo.insert!(%Canobie.User{team_id: 16, name: "rpaz"})
Canobie.Repo.insert!(%Canobie.User{team_id: 16, name: "bwayne"})
Canobie.Repo.insert!(%Canobie.User{team_id: 16, name: "akillelea"})
Canobie.Repo.insert!(%Canobie.Team{id: 17, name: "Team 17"})
Canobie.Repo.insert!(%Canobie.State{team_id: 17, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 17, name: "sholt"})
Canobie.Repo.insert!(%Canobie.User{team_id: 17, name: "mpetito"})
Canobie.Repo.insert!(%Canobie.User{team_id: 17, name: "rcasey"})
Canobie.Repo.insert!(%Canobie.User{team_id: 17, name: "pdurant"})
Canobie.Repo.insert!(%Canobie.Team{id: 18, name: "Team 18"})
Canobie.Repo.insert!(%Canobie.State{team_id: 18, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 18, name: "mkaminski"})
Canobie.Repo.insert!(%Canobie.User{team_id: 18, name: "bsuthoff"})
Canobie.Repo.insert!(%Canobie.User{team_id: 18, name: "pgamache"})
Canobie.Repo.insert!(%Canobie.User{team_id: 18, name: "rhughes"})
Canobie.Repo.insert!(%Canobie.Team{id: 19, name: "Team 19"})
Canobie.Repo.insert!(%Canobie.State{team_id: 19, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 19, name: "mvirzi"})
Canobie.Repo.insert!(%Canobie.User{team_id: 19, name: "abuggia"})
Canobie.Repo.insert!(%Canobie.User{team_id: 19, name: "mtollin"})
Canobie.Repo.insert!(%Canobie.User{team_id: 19, name: "jlavalley"})
Canobie.Repo.insert!(%Canobie.Team{id: 20, name: "Team 20"})
Canobie.Repo.insert!(%Canobie.State{team_id: 20, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 20, name: "mmarrs"})
Canobie.Repo.insert!(%Canobie.User{team_id: 20, name: "cbarry"})
Canobie.Repo.insert!(%Canobie.User{team_id: 20, name: "ahepburn"})
Canobie.Repo.insert!(%Canobie.User{team_id: 20, name: "rmcdermott"})
Canobie.Repo.insert!(%Canobie.Team{id: 21, name: "Team 21"})
Canobie.Repo.insert!(%Canobie.State{team_id: 21, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 21, name: "mpopa"})
Canobie.Repo.insert!(%Canobie.User{team_id: 21, name: "jlevine"})
Canobie.Repo.insert!(%Canobie.User{team_id: 21, name: "rdailey"})
Canobie.Repo.insert!(%Canobie.User{team_id: 21, name: "hdemiroers"})
Canobie.Repo.insert!(%Canobie.Team{id: 22, name: "Team 22"})
Canobie.Repo.insert!(%Canobie.State{team_id: 22, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 22, name: "wcatron"})
Canobie.Repo.insert!(%Canobie.User{team_id: 22, name: "tlawrence"})
Canobie.Repo.insert!(%Canobie.User{team_id: 22, name: "jcough"})
Canobie.Repo.insert!(%Canobie.User{team_id: 22, name: "mnamasivayam"})
Canobie.Repo.insert!(%Canobie.Team{id: 23, name: "Team 23"})
Canobie.Repo.insert!(%Canobie.State{team_id: 23, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 23, name: "raggarwal"})
Canobie.Repo.insert!(%Canobie.User{team_id: 23, name: "mdziuban"})
Canobie.Repo.insert!(%Canobie.User{team_id: 23, name: "kkruity"})
Canobie.Repo.insert!(%Canobie.User{team_id: 23, name: "cmcmillan"})
Canobie.Repo.insert!(%Canobie.Team{id: 24, name: "Team 24"})
Canobie.Repo.insert!(%Canobie.State{team_id: 24, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 24, name: "rhawkes"})
Canobie.Repo.insert!(%Canobie.User{team_id: 24, name: "wtherrien"})
Canobie.Repo.insert!(%Canobie.User{team_id: 24, name: "cjelly"})
Canobie.Repo.insert!(%Canobie.User{team_id: 24, name: "ehalpin"})
Canobie.Repo.insert!(%Canobie.Team{id: 25, name: "Team 25"})
Canobie.Repo.insert!(%Canobie.State{team_id: 25, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 25, name: "scarr"})
Canobie.Repo.insert!(%Canobie.User{team_id: 25, name: "rmarscher"})
Canobie.Repo.insert!(%Canobie.User{team_id: 25, name: "ysamlan"})
Canobie.Repo.insert!(%Canobie.User{team_id: 25, name: "abrink"})
Canobie.Repo.insert!(%Canobie.Team{id: 26, name: "Team 26"})
Canobie.Repo.insert!(%Canobie.State{team_id: 26, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 26, name: "smarshall"})
Canobie.Repo.insert!(%Canobie.User{team_id: 26, name: "jrounds"})
Canobie.Repo.insert!(%Canobie.User{team_id: 26, name: "sghael"})
Canobie.Repo.insert!(%Canobie.User{team_id: 26, name: "scox"})
Canobie.Repo.insert!(%Canobie.Team{id: 27, name: "Team 27"})
Canobie.Repo.insert!(%Canobie.State{team_id: 27, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 27, name: "mhebert"})
Canobie.Repo.insert!(%Canobie.User{team_id: 27, name: "icharny"})
Canobie.Repo.insert!(%Canobie.User{team_id: 27, name: "bzeligson"})
Canobie.Repo.insert!(%Canobie.User{team_id: 27, name: "sbleczinski"})
Canobie.Repo.insert!(%Canobie.Team{id: 28, name: "Team 28"})
Canobie.Repo.insert!(%Canobie.State{team_id: 28, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 28, name: "lkavney"})
Canobie.Repo.insert!(%Canobie.User{team_id: 28, name: "tharward"})
Canobie.Repo.insert!(%Canobie.User{team_id: 28, name: "rboccuzzi"})
Canobie.Repo.insert!(%Canobie.User{team_id: 28, name: "sscarpato"})
Canobie.Repo.insert!(%Canobie.Team{id: 29, name: "Team 29"})
Canobie.Repo.insert!(%Canobie.State{team_id: 29, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 29, name: "sdavis"})
Canobie.Repo.insert!(%Canobie.User{team_id: 29, name: "mclausen"})
Canobie.Repo.insert!(%Canobie.User{team_id: 29, name: "dmcnamara"})
Canobie.Repo.insert!(%Canobie.User{team_id: 29, name: "jliebrock"})
Canobie.Repo.insert!(%Canobie.Team{id: 30, name: "Team 30"})
Canobie.Repo.insert!(%Canobie.State{team_id: 30, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 30, name: "smccauley"})
Canobie.Repo.insert!(%Canobie.User{team_id: 30, name: "mpatey"})
Canobie.Repo.insert!(%Canobie.User{team_id: 30, name: "fgonzalez"})
Canobie.Repo.insert!(%Canobie.User{team_id: 30, name: "jjang"})
Canobie.Repo.insert!(%Canobie.Team{id: 31, name: "Team 31"})
Canobie.Repo.insert!(%Canobie.State{team_id: 31, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 31, name: "scastillo"})
Canobie.Repo.insert!(%Canobie.User{team_id: 31, name: "dthompson"})
Canobie.Repo.insert!(%Canobie.User{team_id: 31, name: "dhoch"})
Canobie.Repo.insert!(%Canobie.User{team_id: 31, name: "dflynn"})
Canobie.Repo.insert!(%Canobie.Team{id: 32, name: "Team 32"})
Canobie.Repo.insert!(%Canobie.State{team_id: 32, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 32, name: "tmcmahon"})
Canobie.Repo.insert!(%Canobie.User{team_id: 32, name: "jbooth"})
Canobie.Repo.insert!(%Canobie.User{team_id: 32, name: "ckim"})
Canobie.Repo.insert!(%Canobie.User{team_id: 32, name: "cgallo"})
Canobie.Repo.insert!(%Canobie.Team{id: 33, name: "Team 33"})
Canobie.Repo.insert!(%Canobie.State{team_id: 33, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 33, name: "zbukhari"})
Canobie.Repo.insert!(%Canobie.User{team_id: 33, name: "dchurchill"})
Canobie.Repo.insert!(%Canobie.User{team_id: 33, name: "aavagyan"})
Canobie.Repo.insert!(%Canobie.User{team_id: 33, name: "msullivan"})
Canobie.Repo.insert!(%Canobie.Team{id: 34, name: "Team 34"})
Canobie.Repo.insert!(%Canobie.State{team_id: 34, state: Canobie.State.starting_state})
Canobie.Repo.insert!(%Canobie.User{team_id: 34, name: "zkovat"})
Canobie.Repo.insert!(%Canobie.User{team_id: 34, name: "sriehlin"})
Canobie.Repo.insert!(%Canobie.User{team_id: 34, name: "iasaff"})
Canobie.Repo.insert!(%Canobie.User{team_id: 34, name: "rpenrose"})
